### ISSUE TITLE
Crashes on shallow clones due to not finding/erroneous commits in revwalk

### ISSUE THREAD

**Issue by mlange-42** [mlange-42/git-graph#47]
```
Error { code: -3, klass: 9, message: "object not found - no match for id (64255bd4ea758a03eba9f7289de6f792dee557e3)" }
```

in

```rust
for oid in revwalk {
    let oid = oid.unwrap();
}
```

EDIT: Seems to be caused by this `libgit2` issue: https://github.com/libgit2/libgit2/issues/3058
The solution is also there: hide commits listed in `.git/shallow`.

**Comment by mlange-42** [comment]
Hiding entries of `.git/shallow` does not help as the list contains the last fetched commits.

Hiding their parents does not work, as `RevWalk::hide()` on them gives an error `object not found`.

@adamreichold Any ideas?

**Comment by adamreichold** [comment]
I am not sure yet I understand where the error is triggered. Is `oid.unwrap()` panicking? If so, couldn't you just start handling the error instead? Or is the error internal to `revwalk.next()`?

**Comment by mlange-42** [comment]
The problem it that there is only this one problematic commit in the revwalk, but no further.
