### ISSUE TITLE
Standard log graph model

### ISSUE THREAD

**Issue by kalvinpearce** [mlange-42/git-graph#53]
I love the styling of the output of this tool and would like to use it more but I am so used to the standard log graph. I see you've got support for custom models, would it be possible to create a model that mimics the look of the standard log graph? And if so how might one go about doing that?

**Comment by mlange-42** [comment]
You can define custom models, see the resp. [manual section](https://github.com/mlange-42/git-graph/blob/master/docs/manual.md#custom-branching-models).

If you mean the curvy branches og the normal git log, then no. This is not supported. Branches are always straight.

**Comment by kalvinpearce** [comment]
No worries, thanks for the reply.
